language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - development

php:
  - 5.3
  - 5.6
  - 7.0

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=1

before_install:
- composer require phpunit/phpunit satooshi/php-coveralls
- composer install

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
- "./vendor/bin/phpunit --configuration phpunit.xml --coverage-clover ./tests/logs/clover.xml"

after_script:
- php vendor/bin/coveralls -v
